Max token error handling
digitalbazaar/bedrock-vue-wallet pull request #73
Opened 2023-11-07 21:51 UTC by jameseaster

#### _Resolves #45 & Resolves [529](https://github.com/digitalbazaar/veres-wallet/issues/529) from Veres Wallet_

---

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

- Bug fix to allow user to see email code error and continue with the login process.

<br/>

### What is the current behavior? (You can also link to an open issue here)

- A max of 5 email tokens can be sent to a user to login. If this limit is exceeded no more tokens will be sent and the form is reset not allowing a user to enter a previously sent email token.

<br/>

### What is the new behavior?

- A user will now be notified of any error when the send email function is not completed successfully. Additionally, if the user sends themself more than 5 tokens, the max token error will be shown and the user can still go to their inbox and utilize the latest email token to continue the login process.

<br/>

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

- [ ] Yes
- [X] No

<br/>

### How has this been tested?

- This has been tested locally with Veres Wallet. This update can handle errors pertaining to the max of 5 outstanding email tokens as well as other errors in the login process.

<br/>

### Screenshots:

> Notification when too many email token requests have been made
> 
> <img  alt="error_notification" width="600" src="https://github.com/digitalbazaar/bedrock-vue-wallet/assets/56396286/fe890761-424d-4615-9e9d-e66495ab2e97" />

2023-11-07 22:07 UTC, dlongley requested changes
While simply accepting this PR would be an improvement over what we have today -- I think we should try to do a bit better. I would expect that most users will not understand the error message about 5 tokens -- so can we show them something a bit better? Perhaps text around "too many login attempts" in a short period of time?

Also, it would be ideal if the frontend checks for this using the semantic `error.name` value instead of using the English error message (if that's possible).

2023-11-08 16:20 UTC, jameseaster commented
@dlongley These are some of the properties from the `max-5-tokens` error:

> ### Error.name
> ```js
> "HTTPError"
> ```

<br/>

<br/>

> ### Error.data
> ```json
> {
>   "name": "NotAllowedError",
>   "type": "NotAllowedError",
>   "message": "No more than 5 tokens can be pending at once.",
>   "cause": null,
>   "details": { "httpStatusCode": 400},
>   "stack": "NotAllowedError: No more than 5...at _addNonceToken.../index.js:68:9"
> }
>```

<br/>

<br/>

> ### Error.message
> ```js
> "No more than 5 tokens can be pending at once."
> ```

<br/>

<br/>

Of those options I thought the most identifiable for this specific error would be looking for the substring of "No more than 5 tokens" in the error message in order to identify this specific error. Once this error has been identified we could certainly customize the error message to be more human friendly like, "Too many email requests, check email for login code."

What are your thoughts?

2023-11-09 16:55 UTC, dlongley commented
@jameseaster,

>  Once this error has been identified we could certainly customize the error message to be more human friendly like, "Too many [login] requests, check [your] email for a login code."

Yes, let's do something like that.

2023-11-09 16:58 UTC, dlongley commented
Once this is ready, the plan is to merge this (#73) and do a minor release, then we'll need a rebase for #66, which I'll go ahead and merge w/o quasar updates, and then rebase #72 and do a major release. We'll get the quasar updates in later in another major release to prevent further hold ups.

2023-11-09 18:28 UTC, jameseaster commented
New custom error message when too many tokens have been requested: 
```
'Too many login requests, check your email for a login code.'
```

<br/>

<img src="https://github.com/digitalbazaar/bedrock-vue-wallet/assets/56396286/9759434f-dee7-46d3-8cd5-d3e36eb35291" alt="screenshot" width="700" />

2023-11-09 19:51 UTC, dlongley approved these changes
Great, thanks!

2023-11-09 19:51 UTC, merged